highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Sivakumar Vunnam
email: sivakumarvunnam1@gmail.com
description: Website of Sivakumar Vunnam, Staff DevOps Engineer at Blackhawk Network Inc
keywords: sivakumar, vunnam, devops, Blackhawk Network, github
baseurl: ""
url: sivakumarvunnam.devops.github.io
name: Sivakumar Vunnam\'s blog
author:
  name: Sivakumar Vunnam
  email: sivakumarvunnam1@gmail.com
